### ISSUE TITLE
Status of ExperimentalDesign.jl?

### ISSUE THREAD

**Issue by versipellis** [phrb/ExperimentalDesign.jl#1]
I'm looking to use this package to do optimal design of experiments - what's the status of it? I've poked through the docs, but am not 100% sure on how everything all goes together.

**Comment by phrb** [comment]
Hi, I'm still working on it and I'm really interested in collaborators, be it to contribute code, tests, or using what is implemented!

So far you can build Plackett Burman screening designs and Full Factorial designs. I've also implemented samplers of random designs using Distributions from the Distributions package and functions to compute some optimal design criteria.

What would you like to do with this package? This could be helpful to plan ahead and decide what to work on next.

**Comment by caseykneale** [comment]
I'm also very curious about this package. My interests are primarily in mixture design. I'd love to have some I and D-optimal mixture designs. I started writing some code then found you were working in this domain and stopped,

https://github.com/caseykneale/ChemometricsTools.jl/blob/master/src/DOE.jl

feel free to borrow and/or change any code there (MIT licensed and you have my permission!)

**Comment by phrb** [comment]
Thanks for sharing @caseykneale, I'll be sure to take a look, Chemometrics looks nice!

I've implemented some functions for optimal design construction but they are not yet working well with the package. I'll be working more intensely on it in the next few months, polishing what is already there and working on the optimal design features.
